Unhandled exception in internal background task 'check'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/Desktop/Albert/cogs/Announcements/announcements.py", line 39, in check
    await channel.send(embed = embed)
AttributeError: 'NoneType' object has no attribute 'send'
Starting Bot...
Bot is ready
Task exception was never retrieved
future: <Task finished coro=<Loop._loop() done, defined at /usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py:88> exception=AttributeError("'NoneType' object has no attribute 'send'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/pi/Desktop/Albert/cogs/Announcements/announcements.py", line 39, in check
    await channel.send(embed = embed)
AttributeError: 'NoneType' object has no attribute 'send'
_ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_message coro=<bound method BotBase.on_message of <discord.ext.commands.bot.Bot object at 0xb66a6130>> exception=SystemExit(None)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 979, in on_message
    await self.process_commands(message)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/Desktop/Albert/cogs/Kill/off.py", line 34, in off
    exit()
  File "/usr/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
